/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SubSubIdImport } from './routes/sub.$subId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubSubIdRoute = SubSubIdImport.update({
  id: '/sub/$subId',
  path: '/sub/$subId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sub/$subId': {
      id: '/sub/$subId'
      path: '/sub/$subId'
      fullPath: '/sub/$subId'
      preLoaderRoute: typeof SubSubIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sub/$subId': typeof SubSubIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sub/$subId': typeof SubSubIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sub/$subId': typeof SubSubIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sub/$subId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sub/$subId'
  id: '__root__' | '/' | '/sub/$subId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubSubIdRoute: typeof SubSubIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubSubIdRoute: SubSubIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sub/$subId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sub/$subId": {
      "filePath": "sub.$subId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
